- name: Ensure networkmanager is installed
  become: yes
  pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
    state: present

- name: "Include systemd specific tasks"
  include_tasks: systemd.yml
