- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  when: distribution_file.stat.exists

- name: "Add automatic timezone switching"
  copy:
    src: "{{ role_path }}/files/09-timezone"
    dest: "/etc/NetworkManager/dispatcher.d"
    owner: root
    group: root
    mode: "755"
  become: yes

- name: "Setup mDNS resolution"
  import_role:
    name: avahi
