- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: "Perform tasks for [{{ username }}]"
  block:
    - name: "Ensure {{ user_home }}/.config/autostart exists"
      file:
        path: "{{ user_home }}/.config/autostart"
        state: directory

    - import_tasks: files.yml
  become: yes
  become_user: "{{ username }}"
