- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ ansible_os_family|lower }}.yml"
  when: distribution_file.stat.exists

- name: "Perform tasks for [{{ username }}]"
  block:
    - name: "Ensure {{ user_home }}/.config/autostart exists"
      file:
        path: "{{ user_home }}/.config/autostart"
        state: directory

    - import_tasks: files.yml
  become: yes
  become_user: "{{ username }}"
