- name: "Add [{{ username }}] to sudoers.d"
  lineinfile:
    path: "/etc/sudoers.d/11-{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: "Install yay"
  aur:
    use: makepkg
    name: yay
    state: present
  become: yes
  become_user: "{{ username }}"
