- name: "Perform os setup tasks as root"
  block:
    - name: "Check for sublime-text gpg key"
      shell: "pacman-key --list-sigs Sublime"
      register: sublime_key
      failed_when: ( sublime_key.rc not in [ 0, 1 ] )
      changed_when: False

    - name: "Install sublime-text repo gpg key"
      shell: "curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg"
      args:
        warn: no
      when: sublime_key.rc == 1

    - name: "Ensure reflector and pacman-contrib are installed"
      pacman:
        name:
          - pacman-contrib
          - reflector
        state: present
        update_cache: yes

    - name: "Update mirrors"
      command: "reflector --country 'United States' --latest 200 --age 24 --sort rate --save /etc/pacman.d/mirrorlist"

    - import_tasks: backup.yml

    - import_tasks: files.yml

    - name: "Perform system upgrade"
      pacman:
        update_cache: yes
        upgrade: yes

    - name: "Ensure base and base-devel are installed"
      pacman:
        name:
          - base
          - base-devel
        state: present
  become: yes

- import_tasks: aur.yml
  when: enable_aur|bool
