- name: Link settings file
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ user_home }}/.config/Code/User/settings.json"
    state: link

- name: Link keybindings file
  file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "{{ user_home }}/.config/Code/User/keybindings.json"
    state: link
