- name: "Ensure Avahi and related applications are installed"
  become: yes
  pacman:
    name:
      - avahi
      - nss-mdns
    state: present

- name: "Include systemd specific tasks"
  include_tasks: systemd.yml
