- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ distribution_file.stat.path }}"
  when: distribution_file.stat.exists

- name: Sync nsswitch.conf file
  synchronize:
    src: "{{ role_path }}/files/nsswitch.conf"
    dest: "/etc/nsswitch.conf"
    archive: no
    checksum: yes
  become: yes
