
- name: Link zshenv
  file:
    src: "{{ role_path }}/files/.zshenv"
    dest: "{{ user_home }}/.zshenv"
    state: link

- name: Link zshrc
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    state: link

- name: Link Zinit bootstraper
  file:
    src: "{{ role_path }}/files/.zinit-bootstrap.zsh"
    dest: "{{ user_home }}/.zinit-bootstrap.zsh"
    state: link
  when: zsh_zinit|bool

- name: Link aliases
  file:
    src: "{{ role_path }}/files/aliases.zsh"
    dest: "{{ user_home }}/.zsh/aliases/zsh.zsh"
    state: link

- name: Link completions script
  file:
    src: "{{ role_path }}/files/completion.zsh"
    dest: "{{ user_home }}/.zsh/scripts/completion.zsh"
    state: link

- name: "Link completions"
  file:
    src: "{{ role_path }}/files/completions"
    dest: "{{ user_home }}/.zsh/completions"
    state: link
