
- name: Link zshenv file
  file:
    src: "{{ role_path }}/files/.zshenv"
    dest: "{{ user_home }}/.zshenv"
    state: link

- name: Link zshrc file
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    state: link

- name: Link zplugin-init file
  file:
    src: "{{ role_path }}/files/.zplugin-init.zsh"
    dest: "{{ user_home }}/.zplugin-init.zsh"
    state: link
  when: zsh_zplugin|bool

- name: Link aliases file
  file:
    src: "{{ role_path }}/files/aliases.zsh"
    dest: "{{ user_home }}/.zsh/aliases/zsh.zsh"
    state: link

- name: Link completions.zsh file
  file:
    src: "{{ role_path }}/files/completion.zsh"
    dest: "{{ user_home }}/.zsh/scripts/completion.zsh"
    state: link

- name: "Link .zsh/completions directory"
  file:
    src: "{{ role_path }}/files/completions"
    dest: "{{ user_home }}/.zsh/completions"
    state: link
