- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ distribution_file.stat.path }}"
  when: distribution_file.stat.exists

- name: "Change root's shell to zsh"
  become: yes
  user:
    name: "root"
    shell: /bin/zsh

- name: "Change [{{ username }}]'s shell to zsh"
  become: yes
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: "Perform tasks for [{{ username }}]"
  block:
    - name: "Make .zsh directory"
      file:
        path: "{{ user_home }}/.zsh"
        state: directory

    - name: "Make .zsh/aliases directory"
      file:
        path: "{{ user_home }}/.zsh/aliases"
        state: directory

    - name: "Make .zsh/env directory"
      file:
        path: "{{ user_home }}/.zsh/env"
        state: directory

    - name: "Make .zsh/scripts directory"
      file:
        path: "{{ user_home }}/.zsh/scripts"
        state: directory

    - import_tasks: backup.yml

    - import_tasks: files.yml

    - import_tasks: zinit.yml
      when: zsh_zinit|bool
  become: yes
  become_user: "{{ username }}"
