- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ distribution_file.stat.path }}"
  when: distribution_file.stat.exists

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: files.yml

    - name: "Copy autostart files"
      copy:
        src: "/etc/xdg/autostart/{{ item }}"
        dest: "{{ user_home }}/.config/autostart/"
        force: no
      with_items:
        - gnome-keyring-secrets.desktop
        - gnome-keyring-ssh.desktop

    - name: "Remove 'OnlyShowIn' from autostart files"
      lineinfile:
        path: "{{ user_home }}/.config/autostart/{{ item }}"
        regexp: "^OnlyShowIn.*$"
        state: absent
      with_items:
        - gnome-keyring-secrets.desktop
        - gnome-keyring-ssh.desktop
  become: yes
  become_user: "{{ username }}"
