- name: "Check for distribution role"
  stat:
    path: "roles/{{ ansible_distribution|lower }}"
  register: distribution_role

- name: "Include distribution specific role"
  include_role:
    name: "{{ ansible_os_family|lower }}"
  when: distribution_role.stat.exists

- name: Sync sudoers file
  synchronize:
    src: "{{ role_path }}/files/sudoers"
    dest: "/etc/sudoers"
    archive: no
    checksum: yes
  become: yes
