- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: files.yml

    - name: "Create .gitconfig-private"
      template:
        src: "{{ role_path }}/files/.gitconfig-private.j2"
        dest: "{{ user_home }}/.gitconfig-private"
  become: yes
  become_user: "{{ username }}"
