- name: "Link .emacs.d"
  file:
    src: "{{ role_path }}/files/.emacs.d"
    dest: "{{ user_home }}/.emacs.d"
    state: link

- name: "Link {{ role_name }} aliases file"
  file:
    src: "{{ role_path }}/files/aliases.zsh"
    dest: "{{ user_home }}/.zsh/aliases/{{ role_name }}.zsh"
    state: link
