- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ distribution_file.stat.path }}"
  when: distribution_file.stat.exists

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: files.yml
  become: yes
  become_user: "{{ username }}"
