- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: files.yml
  become: yes
  become_user: "{{ username }}"
