- name: "Install Base Desktop Packages"
  become: yes
  pacman:
    name:
      - xdg-user-dirs
      - xorg

- name: "Install AMD Drivers if required"
  become: yes
  pacman:
    name:
      - lib32-libva-mesa-driver
      - lib32-mesa
      - lib32-mesa-vdpau
      - libva-mesa-driver
      - mesa
      - mesa-vdpau
      - xf86-video-amdgpu
  when: amd_gpu_check.rc == 0

- name: "Install Intel Drivers if required"
  become: yes
  pacman:
    name:
      - xf86-video-intel
      - mesa
      - lib32-mesa
      - intel-media-driver
  when: intel_gpu_check.rc == 0

- name: "Install Nvidia Drivers if required"
  become: yes
  pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - lib32-nvidia-utils
  when: nvidia_gpu_check.rc == 0

- name: "Ensure base themes are installed"
  become: yes
  pacman:
    name:
      - arc-gtk-theme
      - gnome-icon-theme
    state: present

- name: "Ensure base themes from AUR are installed"
  aur:
    name: papirus-icon-theme-git
    state: present
  become: yes
  become_user: "{{ username }}"
