- name: "Check for AMD GPU"
  shell: |
    set -o pipefail
    if [[ $(lspci | grep AMD) ]]; then exit 0; else exit 1; fi
  register: amd_gpu_check
  failed_when: ( amd_gpu_check.rc not in [ 0, 1 ] )
  changed_when: False

- name: "Check for Intel GPU"
  shell: |
    set -o pipefail
    if [[ $(lspci | grep Intel) ]]; then exit 0; else exit 1; fi
  register: intel_gpu_check
  failed_when: ( intel_gpu_check.rc not in [ 0, 1 ] )
  changed_when: False

- name: "Check for Nvidia GPU"
  shell: |
    set -o pipefail
    if [[ $(lspci | grep NVIDIA) ]]; then exit 0; else exit 1; fi
  register: nvidia_gpu_check
  failed_when: ( nvidia_gpu_check.rc not in [ 0, 1 ] )
  changed_when: False

- name: "Check for Bluetooth"
  shell: |
    set -o pipefail
    dmesg | grep -i blue
  register: bluetooth_check
  failed_when: ( bluetooth_check.rc not in [ 0, 1 ] )
  changed_when: False

- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- import_role:
    name: bluetooth
  when: bluetooth_check|bool

- name: "Perform tasks for [{{ username }}]"
  block:
    - name: "Generate XDG user directories"
      command: "xdg-user-dirs-update"
      async: 1
      poll: 0

    - name: "Make Wallpapers Dir"
      file:
        path: "{{ user_home }}/Pictures/Wallpapers"
        state: directory

    - name: "Copy wallpapaer to wallpapers dir"
      copy:
        src: "{{ role_path }}/files/penrose-triangle.jpg"
        dest: "{{ user_home }}/Pictures/Wallpapers/penrose-triangle.jpg"
  become: yes
  become_user: "{{ username }}"
