- name: "Check for distribution task file"
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution|lower }}.yml"
  register: distribution_file

- name: "Include distribution specific tasks"
  include_tasks: "{{ distribution_file.stat.path }}"
  when: distribution_file.stat.exists

- name: "Install Google Sans font"
  copy:
    src: "{{ role_path }}/files/GoogleSans"
    dest: "/usr/share/fonts/GoogleSans"
  become: yes

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: backup.yml

    - name: "Make fontconfig/conf.d directory"
      file:
        path: "{{ user_home }}/.config/fontconfig/conf.d"
        state: directory

    - import_tasks: files.yml
  become: yes
  become_user: "{{ username }}"
