- import_tasks: archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: "Install Google Sans font"
  copy:
    src: "{{ role_path }}/files/GoogleSans"
    dest: "/usr/share/fonts/GoogleSans"
  become: yes

- name: "Perform tasks for [{{ username }}]"
  block:
    - import_tasks: backup.yml

    - name: "Make fontconfig/conf.d directory"
      file:
        path: "{{ user_home }}/.config/fontconfig/conf.d"
        state: directory

    - import_tasks: files.yml

    - name: Disable embedded bitmap for all fonts
      file:
        src: "/etc/fonts/conf.avail/70-no-bitmaps.conf"
        dest: "{{ user_home }}/.config/fontconfig/conf.d/70-no-bitmaps.conf"
        state: link

    - name: Enable sub-pixel RGB rendering
      file:
        src: "/etc/fonts/conf.avail/10-sub-pixel-rgb.conf"
        dest: "{{ user_home }}/.config/fontconfig/conf.d/10-sub-pixel-rgb.conf"
        state: link

    - name: Enable LCD filter
      file:
        src: "/etc/fonts/conf.avail/11-lcdfilter-default.conf"
        dest: "{{ user_home }}/.config/fontconfig/conf.d/11-lcdfilter-default.conf"
        state: link
  become: yes
  become_user: "{{ username }}"
